### PR TITLE
add into cli

### PR DESCRIPTION
**Pull request by mrocklin**
```
$ head foo.csv
name,balance
Alice,100
Bob,200

$ into foo.csv foo.json

$ head foo.json
{"balance": 100, "name": "Alice"}
{"balance": 200, "name": "Bob"}

$ into foo.csv mongodb://localhost/db::foo
$ into foo.csv postgresql://postgres:postgres@localhost::foo --has-header True
```

### CODE REVIEW

**Comment by mrocklin** [comment]
I'll probably rename `pandat` to just `into`

**Comment by quasiben** [comment]
LGTM!

**Comment by mrocklin** [comment]
See also future work at https://github.com/ContinuumIO/into/issues/79

**Comment by mrocklin** [comment]
@quasiben should `parse` strip quotes from arguments?

**Comment by mrocklin** [comment]
Merging this.  We can iterate in the future.

**Pull request merged**
